// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3v7_vSokXEHs5o9njStVLxiUunC5FtY',
    appId: '1:513173761878:web:842da7632d2ceb757f70f7',
    messagingSenderId: '513173761878',
    projectId: 'chat-app-55c44',
    authDomain: 'chat-app-55c44.firebaseapp.com',
    storageBucket: 'chat-app-55c44.appspot.com',
    measurementId: 'G-5PS0YDMS14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKDXLCRdaGMUHZJnebBYGN_K8Slj3ID0',
    appId: '1:513173761878:android:3ee7f1dc97a9e0b87f70f7',
    messagingSenderId: '513173761878',
    projectId: 'chat-app-55c44',
    storageBucket: 'chat-app-55c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyPtxYAktcZlQryACOZpmJtGsnX4WoJn8',
    appId: '1:513173761878:ios:ee4b063579cfe6557f70f7',
    messagingSenderId: '513173761878',
    projectId: 'chat-app-55c44',
    storageBucket: 'chat-app-55c44.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyPtxYAktcZlQryACOZpmJtGsnX4WoJn8',
    appId: '1:513173761878:ios:ee4b063579cfe6557f70f7',
    messagingSenderId: '513173761878',
    projectId: 'chat-app-55c44',
    storageBucket: 'chat-app-55c44.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn3v7_vSokXEHs5o9njStVLxiUunC5FtY',
    appId: '1:513173761878:web:063ed1f8e366b1997f70f7',
    messagingSenderId: '513173761878',
    projectId: 'chat-app-55c44',
    authDomain: 'chat-app-55c44.firebaseapp.com',
    storageBucket: 'chat-app-55c44.appspot.com',
    measurementId: 'G-JPNGDNKGJM',
  );
}
